### ISSUE TITLE
MovieTexture not found

### ISSUE THREAD

**Issue by imtrobin** [Arvtesh/UnityFx.Async#3]
Hi, build error in AsyncWWW.cs on 5.6.6, MovieTexture class not found, I notice you are using 

#if !UNITY_2018_2_OR_NEWER

for MovieTexture class, I think it should be 

#if UNITY_2018_2_OR_NEWER

**Comment by Arvtesh** [comment]
Hi, @imtrobin. I'm not able to reproduce the issue using Unity 5.6.6. There is no compile errors for me. 
The `#if !UNITY_2018_2_OR_NEWER` define is needed because `MovieTexture` class has been deprecated in Unity 2018.2.

That said, if you could provide more details on the issue, I can investigate it further.

**Comment by imtrobin** [comment]
It doesn't happen in editor, try making an Android build. I had errors during build and I had to remove the ! to build the apk.
