### ISSUE TITLE
can you support to async function for unitask?

### ISSUE THREAD

**Issue by Qusdrok** [Arvtesh/UnityFx.Async#6]
hi guys, i'm using unitask and i need something like progress during task running and i found this package by arvtesh, it's very good, but it doesn't seem to support unitask ?

**Comment by Arvtesh** [comment]
Hopa, I missed this one. Supporting `UniTask` is out of this package's scope. I'm not going to add this.

As a side note, this library was developed when Unity didn't have support for Tasks. Since .NET 4.6 support was added, I'd suggest to just use TPL for majority of use-cases and stay with callbacks for performance-critical code (these is `ValueTask` for some scenarios as well).

**Comment by timcassell** [comment]
@Qusdrok For async progress, I'd suggest checking out my [ProtoPromise](https://github.com/timcassell/ProtoPromise) library.
